SELECT
    PCPEDC.NUMPED AS numeroPedido,
    PCPEDC.DATA AS dataPedido,
    PCPEDC.DTFAT AS dataPedidoFaturado,
    PCPEDC.CODCOB AS codigoCobranca,
    PCPEDC.CODFILIAL AS codigoFilial,
    PCFILIAL.FANTASIA AS filial,
    PCPEDC.CODCLI AS codigoCliente,
    PCCLIENT.CLIENTE AS nomeCliente,
    PCCLIENT.FANTASIA AS nomeFantasiaCliente,
    PCPEDC.VLATEND AS valorFaturadoPedido,
    PCPEDC.VLOUTRASDESP as valorDespesas,
    PCPEDC.VLATEND - PCPEDC.VLOUTRASDESP AS valorLiquidoPedido
FROM PCPEDC
INNER JOIN PCCLIENT ON PCCLIENT.CODCLI = PCPEDC.CODCLI
INNER JOIN PCFILIAL ON PCFILIAL.CODIGO = PCPEDC.CODFILIAL
WHERE PCPEDC.DATA >= TO_DATE('01/01/2025', 'DD/MM/YYYY')
AND PCPEDC.CODFILIAL IN ('31', '52')
AND PCPEDC.POSICAO = 'F'
ORDER BY PCPEDC.DATA