SELECT
    PCPEDI.NUMPED AS numeroPedido,
    PCPEDI.DATA AS dataPedido,
    PCPEDI.CODCLI AS codigoCliente,
    PCCLIENT.CLIENTE AS nomeCliente,
    PCPEDI.CODPROD AS codigoProduto,
    PCPRODUT.DESCRICAO AS produto,
    PCPEDI.QT AS quantidade,
    PCPEDI.PVENDA AS precoVenda,
    PCPEDI.QT * PCPEDI.PVENDA AS subTotalPedido,
    PCPEDI.CODFILIALRETIRA AS codigoFilial,
    PCFILIAL.FANTASIA AS filial
FROM PCPEDI
INNER JOIN PCPRODUT ON PCPRODUT.CODPROD = PCPEDI.CODPROD
INNER JOIN PCCLIENT ON PCCLIENT.CODCLI = PCPEDI.CODCLI
INNER JOIN PCFILIAL ON CODIGO = PCPEDI.CODFILIALRETIRA
WHERE PCPEDI.DATA >= TO_DATE('01/01/2025', 'DD/MM/YYYY')
AND PCPEDI.CODFILIALRETIRA IN ('31', '52')
AND PCPEDI.POSICAO = 'F'
ORDER BY PCPEDI.DATA